"""Figure S1 — APGI Onset Ignition Timeline (0–600 ms).

Multi-track schematic showing normalised APGI variable magnitudes:
  • Sₜ      — precision-weighted prediction-error signal  (paper Eq. 1)
  • θₜ      — allostatic threshold                        (paper Eq. 3)
  • Πᵉ      — exteroceptive effective precision
  • Πⁱ_eff  — interoceptive effective precision           (paper §4.2)

All four variables are normalised to [0, 1] so they are commensurable on
a single y-axis, as specified in the paper's Figure S1 caption.

Annotation tracks correspond to Table 3 (onset ignition timeline):
  Phase 1   0– 80 ms : ε initiation           | N1 / P1
  Phase 2  80–150 ms : Π weighting             | α suppression
  Phase 3 150–300 ms : Sₜ accumulation         | N2 / γ onset
  Phase 4 300–400 ms : Ignition decision        | P3b onset
  Phase 5 400–500 ms : Global broadcast         | Sustained LPC
  Phase 6 ≥500 ms    : Refractory reset         | α rebound

Simulation:
  The four traces are generated by integrating the paper's ODEs
  (Equations 1–4) directly at 1 ms resolution.  This guarantees that
  the figure reflects the publication equations without interference from
  pipeline implementation details that are irrelevant to the illustration.

Usage:
    python examples/figure_s1.py          # saves outputs/figure_s1.png
    make figure-s1                        # via Makefile

Output:
    outputs/figure_s1.png  — 300 dpi publication-ready PNG
"""

from __future__ import annotations

import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# flake8: noqa=E402 (module level import not at top of file - needed for sys.path manipulation)
import matplotlib
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

matplotlib.rcParams["text.usetex"] = False
matplotlib.rcParams["font.family"] = "DejaVu Sans"
matplotlib.rcParams["mathtext.fontset"] = "dejavusans"
matplotlib.rcParams["mathtext.default"] = "regular"


# ---------------------------------------------------------------------------
# Phase annotations — Table 3, paper §4.9
# ---------------------------------------------------------------------------
PHASES: list[tuple[int, int, str, str, str]] = [
    (0, 80, "ε init", "N1 / P1", "#d4e6f1"),
    (80, 150, "Π weight", "α suppress", "#d5e8d4"),
    (150, 300, "Sₜ accum", "N2 / γ", "#fff2cc"),
    (300, 400, "Ignition", "P3b", "#ffddc1"),
    (400, 500, "Broadcast", "LPC", "#e8daef"),
    (500, 600, "Reset", "α rebound", "#f9e79f"),
]


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def _normalize(arr: np.ndarray) -> np.ndarray:
    """Min-max normalise to [0, 1]; returns zeros for constant arrays."""
    lo, hi = float(arr.min()), float(arr.max())
    if hi - lo < 1e-12:
        return np.zeros_like(arr, dtype=float)
    return (arr - lo) / (hi - lo)


def _sigmoid(x: float | np.ndarray, gamma: float = 5.0) -> float | np.ndarray:
    """σ(γ·x) — paper Eq. 2 ignition probability."""
    return 1.0 / (1.0 + np.exp(-np.clip(gamma * x, -500.0, 500.0)))


# ---------------------------------------------------------------------------
# Direct ODE simulation of paper Equations 1–4
# ---------------------------------------------------------------------------
def _simulate_paper_equations(
    dt: float = 0.001,  # 1 ms resolution
    window_ms: int = 600,
    seed: int = 0,
) -> dict:
    """Integrate paper Eq. 1–4 directly at 1 ms resolution.

    Parameters are chosen analytically so that Sₜ first crosses θₜ in
    the 300–400 ms window (Table 3, paper §4.9).

    Paper equations implemented
    ---------------------------
    Eq. 1   Sₜ = Πᵉ·|zᵉ| + Πⁱ_eff·|zⁱ|   (leaky integral)
    Eq. 2   P(Bₜ=1) = σ(γ_sig·(Sₜ − θₜ))
    Eq. 3   dθₜ/dt = −λ_θ(θₜ−θ₀) + κ_meta·Cₜ − Δ_info·Iₜ + η_NE·NE(t)
    Eq. 4   Πⁱ_eff = Πⁱ_baseline · exp(β_SM · M(c,a))

    Returns
    -------
    dict with arrays: S, theta, pi_e, pi_i_eff, B, p_ignite, t_ms
    """
    rng = np.random.default_rng(seed)
    n = window_ms  # 1 step = dt seconds

    # ── Time axis ──────────────────────────────────────────────────────────
    t = np.arange(n) * dt  # seconds
    t_ms = t * 1000.0  # milliseconds (x-axis for plot)

    # ── Stimulus profile ───────────────────────────────────────────────────
    # Exteroceptive error |zᵉ|: zero before stimulus onset, then ramps from
    # 80 ms (after initial thalamo-cortical latency) to a plateau at 250 ms.
    z_e = np.zeros(n)
    ramp_start, ramp_end = 80, 250  # ms
    z_e[ramp_start:ramp_end] = np.linspace(0.0, 0.48, ramp_end - ramp_start)
    z_e[ramp_end:] = 0.48
    z_e += 0.006 * rng.standard_normal(n)
    z_e = np.clip(z_e, 0.0, None)  # |z| is non-negative

    # Interoceptive error |zⁱ|: slow cardiac-rhythm modulation (0.9 Hz ≈ 72 bpm)
    z_i = np.abs(0.18 * np.sin(2 * np.pi * 0.9 * t) + 0.04 * rng.standard_normal(n))

    # ── Precision dynamics ─────────────────────────────────────────────────
    # Πᵉ: rises after stimulus via ACh-mediated gain (80–150 ms window, §4.1)
    # Modelled as a sigmoid onset with τ ≈ 30 ms, plateau = 1.25
    pi_e = 1.0 + 0.3 / (1.0 + np.exp(-(t_ms - 115.0) / 14.0))

    # Πⁱ_eff (paper Eq. 4): Πⁱ_baseline · exp(β_SM · M(c,a))
    # M(c,a) rises slowly (somatic-marker integration), β_SM = 0.35
    # Interoceptive precision shows a slower, cardiac-gated increase
    pi_i_baseline = 0.70
    beta_sm = 0.35
    M = 0.9 * (1.0 - np.exp(-t / 0.22))  # somatic-marker value in [0, +2]
    pi_i_eff = pi_i_baseline * np.exp(beta_sm * M)

    # ── Signal accumulation (paper Eq. 1 + leaky integrator, §4.1.1) ───────
    # Sₜ = Πᵉ·|zᵉ| + Πⁱ_eff·|zⁱ| integrated with time-constant τ_S = 0.28 s
    # Discrete leaky: S(t+1) = (1−λ)·S(t) + λ·S_inst,  λ = dt/τ_S
    tau_S = 0.28
    lam = dt / tau_S
    S_inst = pi_e * z_e + pi_i_eff * z_i
    S = np.zeros(n)
    for k in range(1, n):
        S[k] = (1.0 - lam) * S[k - 1] + lam * S_inst[k]

    # ── Allostatic threshold dynamics (paper Eq. 3) ─────────────────────────
    # dθ/dt = −λ_θ(θ−θ₀) + κ_meta·C − Δ_info·info_value + η_NE·NE(t)
    theta_0 = 0.38  # homeostatic baseline
    lambda_th = 1.2  # restoring rate λ_θ (s⁻¹)
    kappa_m = 0.45  # metabolic cost gain κ_meta
    delta_i = 0.30  # information-value gain Δ_info
    eta_NE = 0.06  # NE coupling
    # NE(t): phasic LC-NE burst coincides with ignition (modelled as Gaussian)
    NE = np.zeros(n)

    C = np.zeros(n)  # metabolic cost (elevated post-ignition)
    info_value = np.zeros(n)  # information value (elevated after broadcast)
    theta = np.full(n, theta_0)
    B = np.zeros(n, dtype=int)
    p_ign = np.zeros(n)

    gamma_sig = 5.0  # sigmoid steepness (paper §4.1.2, γ_sig ∈ [2, 7.5])
    ign_fired = False

    for k in range(1, n):
        # Ignition check (paper Eq. 2)
        p_ign[k] = float(_sigmoid(S[k] - theta[k - 1], gamma_sig))
        if S[k] > theta[k - 1] and not ign_fired:
            B[k] = 1
            ign_fired = True
            # Post-ignition NE burst (Gaussian, σ=15 ms)
            t_ign_ms = t_ms[k]
            NE += 0.9 * np.exp(-0.5 * ((t_ms - t_ign_ms) / 15.0) ** 2)
            # Metabolic cost spike at ignition
            C[k:] = 1.0 * np.exp(-4.0 * (t[k:] - t[k]))
            # Information value rises after broadcast (~400 ms)
            broadcast_start = min(k + 70, n - 1)
            info_value[broadcast_start:] = 0.6 * (
                1.0 - np.exp(-6.0 * (t[broadcast_start:] - t[broadcast_start]))
            )
            # Signal reset: ρ_S = 0.2 (spec §6)
            S[k:] = 0.2 * S[k]

        # Threshold ODE: Euler step (paper Eq. 3)
        dtheta = (
            -lambda_th * (theta[k - 1] - theta_0)
            + kappa_m * C[k]
            - delta_i * info_value[k]
            + eta_NE * NE[k]
        )
        theta[k] = theta[k - 1] + dt * dtheta
        # Refractory boost applied post-ignition (spec §6, pipeline step 9)
        if B[k]:
            theta[k] += 0.55

    return {
        "S": S,
        "theta": theta,
        "pi_e": pi_e,
        "pi_i_eff": pi_i_eff,
        "B": B,
        "p_ignite": p_ign,
        "t_ms": t_ms,
    }


# ---------------------------------------------------------------------------
# Figure generation
# ---------------------------------------------------------------------------
def generate_figure_s1(
    save_path: Path | None = None,
    show: bool = True,
) -> Path:
    """Generate Figure S1 and save as a publication-ready PNG.

    Args:
        save_path: Output path. Defaults to <project_root>/outputs/figure_s1.png.
        show: Call plt.show() after saving.

    Returns:
        Path to the saved file.
    """
    data = _simulate_paper_equations()
    t_ms = data["t_ms"]

    # Normalise each variable to [0, 1] — commensurable on one y-axis (paper spec)
    S_n = _normalize(data["S"])
    theta_n = _normalize(data["theta"])
    pi_e_n = _normalize(data["pi_e"])
    pi_i_n = _normalize(data["pi_i_eff"])

    # First ignition time
    ign_idx = np.where(data["B"] == 1)[0]
    t_ign_ms = float(t_ms[ign_idx[0]]) if len(ign_idx) else None

    # ── Layout: main traces (tall) + annotation track (short) ───────────────
    fig = plt.figure(figsize=(14, 6.5))
    gs = fig.add_gridspec(2, 1, height_ratios=[5, 1.3], hspace=0.04)
    ax_top = fig.add_subplot(gs[0])
    ax_bot = fig.add_subplot(gs[1], sharex=ax_top)

    # ── Phase boundary verticals ──────────────────────────────────────────
    for _, t_bnd, _, _, _ in PHASES[1:]:
        ax_top.axvline(t_bnd, color="#cccccc", linestyle=":", lw=0.9, zorder=1)

    # ── Main traces ────────────────────────────────────────────────────────
    ax_top.plot(t_ms, S_n, lw=2.2, color="#c0392b", label="Sₜ  (signal)", zorder=5)
    ax_top.plot(
        t_ms, theta_n, lw=2.0, color="#2471a3", linestyle="--", label="θₜ  (threshold)", zorder=4
    )
    ax_top.plot(
        t_ms,
        pi_e_n,
        lw=1.7,
        color="#1e8449",
        label="Πᵉ  (exteroceptive precision)",
        zorder=3,
        alpha=0.92,
    )
    ax_top.plot(
        t_ms,
        pi_i_n,
        lw=1.7,
        color="#d68910",
        linestyle="-.",
        label="Πⁱ_eff  (interoceptive precision)",
        zorder=3,
        alpha=0.92,
    )

    # Ignition marker
    if t_ign_ms is not None:
        ax_top.axvline(
            t_ign_ms,
            color="#922b21",
            linestyle=":",
            lw=1.6,
            zorder=6,
            label=f"Ignition Bₜ=1  (t≈{t_ign_ms:.0f} ms)",
        )
        ax_top.annotate(
            "Sₜ > θₜ\n(ignition)",
            xy=(t_ign_ms, 1.02),
            xytext=(t_ign_ms + 22, 1.08),
            fontsize=7.5,
            color="#922b21",
            arrowprops=dict(arrowstyle="->", color="#922b21", lw=1.0),
        )

    ax_top.set_xlim(0, 600)
    ax_top.set_ylim(-0.04, 1.20)
    ax_top.set_ylabel("Normalised magnitude (AU)", fontsize=10)
    ax_top.legend(loc="upper left", fontsize=8.5, framealpha=0.88, ncol=2)
    ax_top.grid(True, alpha=0.22)
    ax_top.set_title(
        "Figure S1 — APGI Onset Ignition Timeline (0–600 ms)\n"
        "Normalised variable magnitudes: Sₜ, θₜ, Πᵉ, Πⁱ_eff  (paper §4.9, Table 3)",
        fontsize=11,
        fontweight="bold",
    )
    plt.setp(ax_top.get_xticklabels(), visible=False)

    # ── Phase annotation track ─────────────────────────────────────────────
    ax_bot.set_xlim(0, 600)
    ax_bot.set_ylim(0, 2)

    for t0, t1, label_short, eeg_label, color in PHASES:
        rect = mpatches.FancyBboxPatch(
            (t0 + 0.5, 0.45),
            (t1 - t0 - 1),
            1.25,
            boxstyle="square,pad=0",
            facecolor=color,
            edgecolor="#999999",
            linewidth=0.8,
            zorder=2,
        )
        ax_bot.add_patch(rect)
        mid = (t0 + t1) / 2.0
        ax_bot.text(
            mid,
            1.22,
            label_short,
            ha="center",
            va="center",
            fontsize=7.8,
            fontweight="bold",
            zorder=3,
        )
        ax_bot.text(
            mid,
            0.72,
            eeg_label,
            ha="center",
            va="center",
            fontsize=6.8,
            color="#444444",
            style="italic",
            zorder=3,
        )

    # Phase boundary verticals on annotation track
    for _, t_bnd, _, _, _ in PHASES[1:]:
        ax_bot.axvline(t_bnd, color="#cccccc", linestyle=":", lw=0.9, zorder=1)

    # Style bottom axis
    for spine in ("top", "right", "left"):
        ax_bot.spines[spine].set_visible(False)
    ax_bot.yaxis.set_visible(False)
    ax_bot.set_xlabel("Time (ms)", fontsize=10)
    ax_bot.set_xticks(range(0, 601, 50))
    ax_bot.tick_params(axis="x", labelsize=8)

    # Tight layout is incompatible with shared-axis gridspec; use subplots_adjust
    fig.subplots_adjust(left=0.07, right=0.98, top=0.90, bottom=0.10)

    # ── Save ──────────────────────────────────────────────────────────────
    if save_path is None:
        out_dir = project_root / "outputs"
        out_dir.mkdir(exist_ok=True)
        save_path = out_dir / "figure_s1.png"

    fig.savefig(save_path, dpi=300, bbox_inches="tight")
    print(f"Figure S1 saved → {save_path}")

    if show:
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            plt.show()

    plt.close(fig)
    return Path(save_path)


if __name__ == "__main__":
    generate_figure_s1()
